server.port=8080
server.address=0.0.0.0

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/shopstack_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


app.jwt.secret=9a2f8c4e7b1d6e3f5a8c9b2d4e6f1a3b5c7d9e2f4a6b8c0d2e4f6a8b0c2d4e6f
app.jwt.expiration-ms=86400000


razorpay.key.id=rzp_test_TOuLwmKFLdG1tS
razorpay.key.secret=8bhpqAwI8u7gYtqBN5t1wnaz

